BOARD_SIZE = 10

EMPTY_CELL_VALUE = 0
PLAYER_ONE_VALUE = 1
PLAYER_TWO_VALUE = 2

PLAYER_ONE_PAWN_COLOR = "White - Top"
PLAYER_TWO_PAWN_COLOR = "Black - Bottom"


TIME_LIMIT = 10  # seconds
MINIMAX_DEPTH = 3

# Game Modes
P_VS_P_MODE = 1
P_VS_MINIMAX = 2
